version: "3"

services:
  jenkins:
    build:
      context: ./jenkins
    deploy:
      labels:
        jenkins.description: "Creating jenkins and adding users"
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
     - jenkins
volumes:
  jenkins_home:

networks:
  jenkins: